###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    db:
      image: mysql:5.6
      container_name: stm-db
      working_dir: /application
      environment:
        - MYSQL_ROOT_PASSWORD=nasko
        - MYSQL_DATABASE=stm
        - MYSQL_USER=stm
        - MYSQL_PASSWORD=stm
      ports:
        - "3333:3306"
      volumes:
          - ./dbdata:/var/lib/mysql

    web:
      image: webdevops/php-apache:ubuntu-15.10
      container_name: stm-web
      volumes:
          - ../backend:/var/www/stm
          - ./stm.conf:/opt/docker/etc/httpd/conf.d/stm.dev.fb.conf
      ports:
       - "8080:80"
      links:
       - db

