###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    db:
      image: mysql:5.6
      container_name: project-db
      working_dir: /application
      environment:
        - MYSQL_ROOT_PASSWORD=nasko
        - MYSQL_DATABASE=project
        - MYSQL_USER=project
        - MYSQL_PASSWORD=project
      ports:
        - "3306:3306"
      volumes:
          - ./dbdata:/var/lib/mysql

    web:
      build: ./web
      container_name: project-web
      volumes:
          - ../project:/var/www/project
          - ./project.conf:/etc/apache2/sites-enabled/project.conf
      ports:
       - "80:80"
      links:
       - db

