###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    db:
      image: mysql:5.6
      container_name: stm-db
      working_dir: /application
      environment:
        - MYSQL_ROOT_PASSWORD=nasko
        - MYSQL_DATABASE=stm
        - MYSQL_USER=stm
        - MYSQL_PASSWORD=stm
      ports:
        - "3333:3306"
      volumes:
          - ./dbdata:/var/lib/mysql

    web:
      build: ./web2
      container_name: stm-web
      volumes:
          - ../backend:/var/www/stm
          - ./stm.conf:/etc/apache2/sites-available/000-default.conf
      ports:
       - "80:80"
      links:
       - db

